version: '3.3'

services:
  db1:
    image: postgres
    restart: always
    hostname: db1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password1
      POSTGRES_DB: database1
    volumes:
      - ./init-script1.sql:/docker-entrypoint-initdb.d/init-script.sql
    ports:
      - 5431:5432

  db2:
    image: postgres
    restart: always
    hostname: db2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password2
      POSTGRES_DB: database2
    volumes:
      - ./init-script2.sql:/docker-entrypoint-initdb.d/init-script.sql
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    depends_on:
      - db1
      - db2
